### ISSUE TITLE
Sample code doesn't work

### ISSUE THREAD

**Issue by remixer-dec** [NodeFactoryIo/fastify-sse-v2#1]
I'm referring to [this ](https://www.npmjs.com/package/fastify-sse-v2#sending-events-from-asynciterable-source)code
and I'm getting this error:
```
UnhandledPromiseRejectionWarning: TypeError: source is not async iterable
    at transformAsyncIterable (node_modules\fastify-sse-v2\lib\sse.js:36:31)
    at transformAsyncIterable.next ...
```

to make it work, I had to do something like this
```javascript
server.get("/", async function (req, res) {
    res.sse(await (async function * source () {
          for (let i = 0; i < 10; i++) {
            //sleep(2000);
            yield {id: String(i), data: "Some message"};
          }
    })())
});
```
not sure if I got the same intended functionality, but at least now it works
_Node v12.16.3_

**Comment by mpetrunic** [comment]
You are right, sorry, I'm missing () in sample code. Will update!

**Comment by mpetrunic** [comment]
fixed in https://github.com/NodeFactoryIo/fastify-sse-v2/commit/f81028cb98f62a1f1a46ec36bfa647876ee5023e
