### ISSUE TITLE
How to know connection is closed on sse?

### ISSUE THREAD

**Issue by dmitry-kostin** [NodeFactoryIo/fastify-sse-v2#2]
Hey quick question here, 
I'm trying to dynamically create event emitters when sse starts, but have no idea how to listen close event (eg when user closed browser tab) to properly destroy event emitter; Is there something I'm missing for?

**Comment by mpetrunic** [comment]
When client closes connection, fastify will call close on internal outputstream which will break `for await` loop. So you can destroy event emitter after for await loop. If you are using EventIterator like in example, returned function is called if connection is closed.

**Comment by dmitry-kostin** [comment]
thank for a fast reply, @mpetrunic 
actually if I run code from example i don't get any "on close" events

so just to illustrate, with following code block:

```const eventEmitter = new EventEmitter();
            res.sse(new EventIterator(
                (push) => {
                    eventEmitter.on('some_event', push);
                    return () => {
                        server.log.info('--- Closed');
                    };
                }),
            );
            server.log.info('--- Connected');
            await snooze(5000);
            eventEmitter.emit('some_event', 'hello world');
```
I got following log:

```
{"msg":"--- Connected","v":1}
{"reqId":3,"err":{"type":"NodeError","message":"Premature close","stack":"Error: Premature close\n    at ServerResponse.onclose (/Users/iwooky/IdeaProjects/builder-v2/builder-api/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:67:73)\n    at ServerResponse.emit (events.js:203:15)\n    at ServerResponse.EventEmitter.emit (domain.js:448:20)\n    at Socket.onServerResponseClose (_http_server.js:172:44)\n    at Socket.emit (events.js:203:15)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at TCP._handle.close (net.js:607:12)","name":"Error","code":"ERR_STREAM_PREMATURE_CLOSE"},"msg":"response terminated with an error with headers already sent","v":1}
{"reqId":3,"err":{"type":"NodeError","message":"Premature close","stack":"Error: Premature close\n    at PassThrough.onclose (/Users/iwooky/IdeaProjects/builder-v2/builder-api/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:62:73)\n    at PassThrough.emit (events.js:203:15)\n    at PassThrough.EventEmitter.emit (domain.js:448:20)\n    at emitCloseNT (internal/streams/destroy.js:68:8)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","name":"Error","code":"ERR_STREAM_PREMATURE_CLOSE"},"msg":"response terminated with an error with headers already sent","v":1}
```

and ideally I use Emittery for events so my preferred usage is like this:
```
     const iterator = emitteryStream.events(['some']);
     res.sse(iterator);
```

with both scenarios i need somehow to know when connection closed, to check if somebody is left on the steam, and if there are nobody I would be able just destroy it

**Comment by mpetrunic** [comment]
It might be bug. I will try that and get back to you

**Comment by mpetrunic** [comment]
https://github.com/NodeFactoryIo/fastify-sse-v2/pull/3

Not sure if I should merge it, because if you checkout changes. You can implement this yourself by listening on `request.req.on("close, () =>)` event

**Comment by dmitry-kostin** [comment]
ya may be you are right, that's a pretty easy way to listen it. May be it's not very obvious, but anyway, I think you helped a much, thanks @mpetrunic

**Comment by mpetrunic** [comment]
I will create PR to update readme with this note
