### ISSUE TITLE
constantly getting an error "Promise may not be fulfilled with 'undefined' when statusCode is not 204"

### ISSUE THREAD

**Issue by izidizi** [NodeFactoryIo/fastify-sse-v2#33]
When I use the example code fastify files an error: _Promise may not be fulfilled with 'undefined' when statusCode is not 204_ (SSE itself works as expected). If I return something or just try to send an empty response using `reply.send()` the error changes to: _Cannot set headers after they are sent to the client_
What is the right way to get rid of those needless errors?

**Comment by mpetrunic** [comment]
Might depend on version but try `reply.sent=true`

**Comment by izidizi** [comment]
awersome, thanks!

**Comment by ilya-adnymics** [comment]
I had the same issue and setting `reply.sent = true` helped solving it. Maybe makes sense to put it in examples?
