### ISSUE TITLE
Example for cleaning up anonymous function (redis pubsub)

### ISSUE THREAD

**Issue by Cluster2a** [NodeFactoryIo/fastify-sse-v2#49]
Hey, I am using the implementation for redis, according to your docs:
```JS
import {FastifySSEPlugin} from "fastify-sse-v2";
import {on} from "events";
import { server } from '../index.js';

const server = fastify();
server.register(FastifySSEPlugin);

server.get("/", function (req, res) {
    const { redis } = server;
    res.sse(
  (async function* () {
    for await (const event of on(redis, "message")) {
      yield {
        type: event.name,
        data: JSON.stringify(event),
      };
    }
  })()
);
});
```
This implementation works fine, but after several requests, I am getting the error `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [ServerResponse]. Use emitter.setMaxListeners() to increase limit`

As you have written in the docs, a cleanup should happen on connection close.
I am wondering how I should unset the listener on an anonymous function.

Is there some example?

Thanks in advance.

**Comment by Cluster2a** [comment]
I came up with the following implementation:
```JS
export const userPipeline = async (request: any, reply: FastifyReply) => {
import { FastifyReply } from 'fastify';
import { on } from 'events';
import { v4 as uuidv4 } from 'uuid';
import { server } from '../index.js';

export const userPipeline = async (request: any, reply: FastifyReply) => {
	const { redis } = server;
	const abortController = new AbortController();

	reply.sse(
		(async function* source() {
			redis.setMaxListeners(2);
			try {
				for await (let event of on(redis, 'message', { signal: abortController.signal })) {
					yield {
						id: uuidv4(),
						type: event.name,
						data: JSON.stringify({ data: 'some data' })
					};
				}
			} catch (error) {
				if (error.name !== 'AbortError') {
					throw error;
				}
			}
		})()
	);

	request.socket.on('close', () => abortController.abort());
};
```
After refreshing the page three times, I won't get the error again since the listener is removed.
I am wondering curious about the `request.socket.on('close', () => abortController.abort());`.

I understand this event is only triggered for cases where the client explicitly closes the connection and doesn't handle cases where the connection was dropped due to a networking outage. In this case, the listeners will remain, or am I wrong on this?

**Comment by mpetrunic** [comment]
@Cluster2a https://github.com/NodeFactoryIo/fastify-sse-v2#note
Pretty sure this will get triggered in any situation when the connection is closed so you should be good to go!

**Comment by dylan1951** [comment]
Kind of weird that the example usage is inherently broken...
