### ISSUE TITLE
session close after 60 seconds of "idle" time?

### ISSUE THREAD

**Issue by paul-bell** [NodeFactoryIo/fastify-sse-v2#56]
Hello, 

I've begun using your fastify-sse-v2.

My curl client terminates after ~60 seconds of idle time:

```
retry: 3000

* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```
By "idle" I mean that the SSE server hasn't received any events in 60 seconds (quite likely in this app) and thus hasn't sent any on to the curl client.

1. Does your plugin close the session after 60 seconds of no events?
2. If so, is this value configurable?
3. If not, do you know where this close is occurring?

I do realize that a real-world client would be reconnecting when this occurs.

Thanks for this plugin, and for your help.

**Comment by mpetrunic** [comment]
> Does your plugin close the session after 60 seconds of no events?

Nope

> If so, is this value configurable?

It's not since plugin is not setting that value

> If not, do you know where this close is occurring?

You can look into fastify's [keepAliveTimeout](https://www.fastify.io/docs/latest/Reference/Server/#keepAliveTimeout). Since you said it's after 60s, do you maybe use nginx? Because, I think, nginx has default keepAlive timeout of 60s

**Comment by paul-bell** [comment]
Thank you very much for your reply; most helpful.

Indeed, nginx is implicated here. I will dig into it and into fastify's keepAliveTimeout.

**Comment by mpetrunic** [comment]
I will close this issue, let me know if something comes up that is plugin responsibility^^
